# Generated by Django 6.0.4 on 2026-04-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='city_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
