# Generated by Django 6.0.4 on 2026-04-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobapplication_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='location',
            field=models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'Onsite')], max_length=20),
        ),
    ]
