# Generated by Django 6.0.4 on 2026-04-20

import django.db.models.deletion
import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobapplication_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter_file',
            field=models.FileField(blank=True, null=True, upload_to='cover_letters/', validators=[jobs.models.validate_upload_extension, jobs.models.validate_upload_size]),
        ),
    ]
