# Generated by Django 6.0.4 on 2026-04-20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobapplication_cover_letter_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='cover_letter_file',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='cover_letter_text',
        ),
    ]
