# Generated by Django 6.0.4 on 2026-04-21 15:14

import jobs.models
from django.db import migrations, models


def copy_cv_file_to_job(apps, schema_editor):
    JobApplication = apps.get_model("jobs", "JobApplication")

    for job in JobApplication.objects.select_related("cv").exclude(cv__isnull=True):
        cv_obj = getattr(job, "cv", None)
        if not cv_obj or not getattr(cv_obj, "file", ""):
            continue
        if job.cv_file:
            continue
        job.cv_file = cv_obj.file
        job.save(update_fields=["cv_file"])


def copy_cv_file_to_job_reverse(apps, schema_editor):
    # CV model is removed in this migration; no reliable reverse data operation is possible.
    return


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_cv_cover_letter_fields'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE jobs_jobapplication ADD COLUMN IF NOT EXISTS cv_file varchar(100)",
                    reverse_sql="ALTER TABLE jobs_jobapplication DROP COLUMN IF EXISTS cv_file",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='jobapplication',
                    name='cv_file',
                    field=models.FileField(blank=True, null=True, upload_to='cvs/', validators=[jobs.models.validate_upload_extension, jobs.models.validate_upload_size]),
                ),
            ],
        ),
        migrations.RunPython(copy_cv_file_to_job, copy_cv_file_to_job_reverse),
        migrations.RemoveConstraint(
            model_name='cv',
            name='uniq_cv_name_version',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='cv',
        ),
        migrations.DeleteModel(
            name='CV',
        ),
    ]
